version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    networks:
      outnet:
        ipv4_address: ${PIHOLE_IP}
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 443/tcp
    environment:
      TZ: 'America/Guatemala'
    volumes:
      - '${DATA_SRV}/pihole/config/:/etc/pihole/'
      - '${DATA_SRV}/pihole/dns/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nfs-server:
    image: fschuindt/docker-nfs-server:2.2.1
    volumes:
      - '${SHARE}:/nfs'
      - '/lib/modules:/lib/modules:ro'
    environment:
      NFS_EXPORT_0: '/nfs *(fsid=0,rw,sync,no_root_squash,no_subtree_check)'
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    ports:
      - 2049:2049

networks:
  outnet:
    driver: macvlan
    driver_opts:
      parent: ${NETINTERFACE}
    ipam:
      config:
        - subnet: '192.168.1.0/24'