version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    networks:
      outnet:
        ipv4_address: '${BASEIP}.2'
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 443/tcp
    environment:
      TZ: 'America/Guatemala'
    volumes:
      - '${DATA_SRV}/pihole/config/:/etc/pihole/'
      - '${DATA_SRV}/pihole/dns/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  nfs-server:
    image: fschuindt/docker-nfs-server:2.2.1
    volumes:
      - '${SHARE}:/nfs'
      - '/lib/modules:/lib/modules:ro'
    environment:
      NFS_EXPORT_0: '/nfs *(fsid=0,rw,sync,no_root_squash,no_subtree_check)'
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    ports:
      - 2049:2049
    restart: unless-stopped
  
  bitlbee:
    image: esturafd/bitlbee-alpine-plugins:latest
    volumes:
      - '${DATA_SRV}/bitlbee:/bitlbee-data'
      - '/usr/share/zoneinfo/America/Guatemala:/etc/localtime:ro'
    ports:
      - 6667:6667
    restart: unless-stopped

  minidlna:
    image: vladgh/minidlna:0.5.0
    networks:
      outnet:
        ipv4_address: '${BASEIP}.9'
    volumes:
      - '${SHARE}/Video:/media/video'
      - '${SHARE}/Audio:/media/audio'
    environment:
      MINIDLNA_MEDIA_DIR_1: 'V,/media/video'
      MINIDLNA_MEDIA_DIR_2: 'A,/media/audio'
    restart: unless-stopped

networks:
  outnet:
    driver: macvlan
    driver_opts:
      parent: ${NETINTERFACE}
    ipam:
      config:
        - subnet: '192.168.1.0/24'