version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    networks:
      outnet:
        ipv4_address: 192.168.1.2
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
      - 443/tcp
    environment:
      TZ: 'America/Guatemala'
    volumes:
      - '/mnt/itzamna/srv/config/:/etc/pihole/'
      - '/mnt/itzamna/srv/dns/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  outnet:
    driver: macvlan
    driver_opts:
      parent: enp4s0
    ipam:
      config:
        - subnet: '192.168.1.0/24'